### ISSUE TITLE
Change content on web

### ISSUE THREAD

**Issue by lakruzz** [prolike/drop-gdpr#1]
Understand how the web is generated - tweak a few bits and parts

**Comment by lakruzz** [comment]
The estimate is a timebox

**Comment by LouBNielsen** [comment]
I'm getting to understand how the webpage is generated.
It is also possible for me to change some of the content.
I'm still can't change the webpage backgroung picture - others have had the same issue.. 

![image](https://user-images.githubusercontent.com/17924001/40611223-c7f15796-6275-11e8-8a0a-3cd7d5e035f5.png)

https://github.com/YouTransfer/YouTransfer/issues/164

**Comment by LouBNielsen** [comment]
It was the cache that caused the issues - even though the cache is handled in the Cache-Control header
